apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      image: tutum/hello-world
      ports:
        - name: www
          containerPort: 80
          hostPort: 80
