apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-controller
spec:
  replicas: 2
  selector:
    demo: hello
  template:
    metadata:
      name: hello-world
      labels:
        demo: hello
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          ports:
            - name: www
              containerPort: 80
