apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    demo: hello
spec:
  containers:
    - name: hello-world
      image: tutum/hello-world
      ports:
        - name: www
          containerPort: 80
